import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { API_URL } from "../../config";

function EditRecord() {
  const { recordId } = useParams(); const navigate = useNavigate();
  const [form, setForm] = useState(null); const [stores, setStores] = useState([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([fetch(`${API_URL}/records/${recordId}`), fetch(`${API_URL}/inventory-options`)]).then(async ([recordResponse, optionsResponse]) => { const [record, options] = await Promise.all([recordResponse.json(), optionsResponse.json()]); if (!recordResponse.ok) throw new Error(record.error || "Unable to load record."); if (!optionsResponse.ok) throw new Error(options.error || "Unable to load branches."); setForm(record); setStores(options.stores || []); }).catch((loadError) => setError(loadError.message)); }, [recordId]);
  const change = ({ target }) => setForm({ ...form, [target.name]: target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API_URL}/records/${recordId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, items_received: Number(form.items_received), items_in_stock: Number(form.items_in_stock), items_spoilt: Number(form.items_spoilt), buying_price: Number(form.buying_price), selling_price: Number(form.selling_price) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to update record."); navigate("/clerk/inventory"); } catch (submitError) { setError(submitError.message); } finally { setSaving(false); } };
  if (!form) return <p style={{ padding: 24 }}>{error || "Loading record…"}</p>;
  return <main style={page}><button onClick={() => navigate("/clerk/inventory")}>← Inventory</button><h1>Edit {form.product_name}</h1>{error && <p role="alert" style={errorStyle}>{error}</p>}<form onSubmit={submit} style={formStyle}><label>Branch<select name="store_name" value={form.store_name} onChange={change}>{stores.map((store) => <option key={store} value={store}>{store}</option>)}</select></label><label>Supplier name<input name="supplier_name" value={form.supplier_name || ""} onChange={change} required /></label>{["items_received", "items_in_stock", "items_spoilt", "buying_price", "selling_price"].map((name) => <label key={name}>{name.replaceAll("_", " ")}<input type="number" name={name} min="0" step={name.includes("price") ? "0.01" : "1"} value={form[name]} onChange={change} required /></label>)}<label>Payment status<select name="payment_status" value={form.payment_status} onChange={change}><option value="unpaid">Unpaid</option><option value="partial">Partial</option><option value="paid">Paid</option></select></label><button disabled={saving} style={primary}>{saving ? "Saving…" : "Save changes"}</button></form></main>;
}
const page = { maxWidth: 660, margin: "0 auto", padding: "32px 20px" }; const formStyle = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))", gap: 16, padding: 22, borderRadius: 14, background: "#F8FAFC", border: "1px solid #E2E8F0" }; const primary = { border: 0, borderRadius: 8, padding: 12, background: "#2563EB", color: "white", fontWeight: 600 }; const errorStyle = { color: "#B91C1C" };
export default EditRecord;